/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package msystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author never
 */
public class AddReport extends javax.swing.JFrame {
    String pattern = "yyyy-MM-dd";
    SimpleDateFormat simpleDate = new SimpleDateFormat(pattern);
    String currentDate = simpleDate.format(new Date());
    String sql = null;
    DBConnect db = new DBConnect();
    Connection con = null;
    PreparedStatement stmt;
    ResultSet result;
    int numberOfCharactersInBox = 0;
    /**
     * Creates new form AddReport
     */
    public AddReport() {
        System.out.println(currentDate);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addReportUserIdTxt = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        addReportDateTxt = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addReportTypeTxt = new javax.swing.JTextArea();
        addReportConfirmBtn = new javax.swing.JButton();
        addReportCancelBtn = new javax.swing.JButton();
        addReportCharCountLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User ID");

        jScrollPane1.setViewportView(addReportUserIdTxt);

        jLabel2.setText("Report Date");

        addReportDateTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        addReportDateTxt.setText(currentDate);

        jLabel3.setText("Report Type");

        addReportTypeTxt.setColumns(20);
        addReportTypeTxt.setLineWrap(true);
        addReportTypeTxt.setRows(5);
        addReportTypeTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addReportTypeTxtFocusLost(evt);
            }
        });
        addReportTypeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addReportTypeTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addReportTypeTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addReportTypeTxtKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(addReportTypeTxt);

        addReportConfirmBtn.setText("Confirm");
        addReportConfirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportConfirmBtnMouseClicked(evt);
            }
        });

        addReportCancelBtn.setText("Cancel");
        addReportCancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportCancelBtnMouseClicked(evt);
            }
        });

        addReportCharCountLbl.setText("# of characters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addReportConfirmBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addReportCancelBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addReportCharCountLbl))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(addReportDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addReportDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addReportCharCountLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReportConfirmBtn)
                    .addComponent(addReportCancelBtn))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addReportConfirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportConfirmBtnMouseClicked
        // TODO add your handling code here:
        //TODO add sql add statement here
        sql = String.format("INSERT INTO reports(UserID, ReportDate, ReportType) VALUES(%s, '%s', '%s')", 
                addReportUserIdTxt.getText(), addReportDateTxt.getText(), addReportTypeTxt.getText());
        //JOptionPane.showMessageDialog(null, sql);
        try {
            con = db.OpenConnection();
            stmt = con.prepareStatement(sql);
            stmt.execute();
            
            if (result != null) {
                System.out.println("Successfully Accessed DataBase to add report");
            }
            /*
            while (result.next()) {
                System.out.print(result.getString("Username") + ", " + result.getString("UserID"));
            }*/
            con.close();
            System.out.println("Database closed");
        }
        catch(Exception e) {
            System.out.println(e);
        }
        MainPage.editEmployee = false;
        this.setVisible(false);
    }//GEN-LAST:event_addReportConfirmBtnMouseClicked

    private void addReportCancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportCancelBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_addReportCancelBtnMouseClicked

    private void addReportTypeTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addReportTypeTxtFocusLost
        // TODO add your handling code here:
        if(addReportTypeTxt.getText().length() > 255){
            JOptionPane.showMessageDialog(null, "Please only enter 255 characters");
        }
    }//GEN-LAST:event_addReportTypeTxtFocusLost

    private void addReportTypeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addReportTypeTxtKeyTyped
        // TODO add your handling code here:
        numberOfCharactersInBox = addReportTypeTxt.getText().length();
        if(numberOfCharactersInBox > 255){
            JOptionPane.showMessageDialog(null, "Please only enter 255 characters");
        }
        //numberOfCharactersInBox.
        addReportCharCountLbl.setText(String.format("%d", numberOfCharactersInBox));
    }//GEN-LAST:event_addReportTypeTxtKeyTyped

    private void addReportTypeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addReportTypeTxtKeyReleased
        // TODO add your handling code here:
        numberOfCharactersInBox = addReportTypeTxt.getText().length();
        if(addReportTypeTxt.getText().length() > 255){
            JOptionPane.showMessageDialog(null, "Please only enter 255 characters");
        }
        addReportCharCountLbl.setText(String.format("%d", numberOfCharactersInBox));
    }//GEN-LAST:event_addReportTypeTxtKeyReleased

    private void addReportTypeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addReportTypeTxtKeyPressed
        // TODO add your handling code here:
        numberOfCharactersInBox = addReportTypeTxt.getText().length();
        addReportCharCountLbl.setText(String.format("%d", numberOfCharactersInBox));
    }//GEN-LAST:event_addReportTypeTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReportCancelBtn;
    private javax.swing.JLabel addReportCharCountLbl;
    private javax.swing.JButton addReportConfirmBtn;
    private javax.swing.JFormattedTextField addReportDateTxt;
    private javax.swing.JTextArea addReportTypeTxt;
    private javax.swing.JTextPane addReportUserIdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables


}
