/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package msystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class AddReport extends javax.swing.JFrame {
    //class level variables
    Employee emp = new Employee();
    boolean mainTextVisible = false;
    String pattern = "yyyy-MM-dd";
    SimpleDateFormat simpleDate = new SimpleDateFormat(pattern);
    String currentDate = simpleDate.format(new Date());
    String sql = null;
    DBConnect db = new DBConnect();
    Connection con = null;
    PreparedStatement stmt;
    ResultSet result;
    int numberOfCharactersInBox = 0;
    /**
     * Creates new form AddReport
     */
    public AddReport() {
        //setting up resiziability of the screen
        System.out.println(currentDate);
        initComponents();
        addReportMainReportTxtBox.setVisible(false);
        addReportMainReportTxtBox.setColumns(0);
        setBounds(0, 0, 439, 439);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addReportUserIdTxt = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        addReportDateTxt = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addReportTypeTxt = new javax.swing.JTextArea();
        addReportConfirmBtn = new javax.swing.JButton();
        addReportCancelBtn = new javax.swing.JButton();
        addReportCharCountLbl = new javax.swing.JLabel();
        addReportOpenMainBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        addReportMainReportTxtBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User ID");

        addReportUserIdTxt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(addReportUserIdTxt);

        jLabel2.setText("Report Date");

        addReportDateTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        addReportDateTxt.setText(currentDate);
        addReportDateTxt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N

        jLabel3.setText("Report Type");

        addReportTypeTxt.setColumns(20);
        addReportTypeTxt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        addReportTypeTxt.setLineWrap(true);
        addReportTypeTxt.setRows(5);
        addReportTypeTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addReportTypeTxtFocusLost(evt);
            }
        });
        addReportTypeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addReportTypeTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addReportTypeTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addReportTypeTxtKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(addReportTypeTxt);

        addReportConfirmBtn.setText("Confirm");
        addReportConfirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportConfirmBtnMouseClicked(evt);
            }
        });

        addReportCancelBtn.setText("Cancel");
        addReportCancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportCancelBtnMouseClicked(evt);
            }
        });

        addReportCharCountLbl.setText("# of characters");

        addReportOpenMainBtn.setText("Show Main Report Form");
        addReportOpenMainBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportOpenMainBtnMouseClicked(evt);
            }
        });

        addReportMainReportTxtBox.setColumns(20);
        addReportMainReportTxtBox.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        addReportMainReportTxtBox.setLineWrap(true);
        addReportMainReportTxtBox.setRows(5);
        addReportMainReportTxtBox.setAutoscrolls(false);
        jScrollPane3.setViewportView(addReportMainReportTxtBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addReportConfirmBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addReportCancelBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addReportCharCountLbl))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(addReportDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addReportOpenMainBtn)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(addReportOpenMainBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addReportDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(addReportCharCountLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addReportConfirmBtn)
                            .addComponent(addReportCancelBtn)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 966, 373);
    }// </editor-fold>//GEN-END:initComponents

    private void addReportConfirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportConfirmBtnMouseClicked
        /*
        Pulls together information from the filled out report screen and sends it 
        to the method that creats the reports and sends them to the database
        then the screen is removed from the users view.
        */
        // add to an arraylist to make a report
        // order UID, Date, report type, data
        ArrayList reportToAdd = new ArrayList<>();
        Collections.addAll(reportToAdd, addReportUserIdTxt.getText(), 
                addReportDateTxt.getText(), addReportTypeTxt.getText(),
                addReportMainReportTxtBox.getText());
        emp.addNewReport(reportToAdd);
        
        this.setVisible(false);
    }//GEN-LAST:event_addReportConfirmBtnMouseClicked

    private void addReportCancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportCancelBtnMouseClicked
        /*
        User does not wish to go through with the report creation, closes
        out the screen
        */
        this.setVisible(false);
    }//GEN-LAST:event_addReportCancelBtnMouseClicked

    private void addReportTypeTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addReportTypeTxtFocusLost
        /*
        This and the methods below are something of a prevention of the user adding more than
        255 characters, sometimes it works on point and sometimes it lags behind
        This method runs when focus is lost on the text box
        */
        if(addReportTypeTxt.getText().length() > 255){
            JOptionPane.showMessageDialog(null, "Please only enter 255 characters");
        }
    }//GEN-LAST:event_addReportTypeTxtFocusLost

    private void addReportTypeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addReportTypeTxtKeyTyped
        // This should run when a key is typed within the box
        numberOfCharactersInBox = addReportTypeTxt.getText().length();
        if(numberOfCharactersInBox > 255){
            JOptionPane.showMessageDialog(null, "Please only enter 255 characters");
        }
        //numberOfCharactersInBox.
        addReportCharCountLbl.setText(String.format("%d", numberOfCharactersInBox));
    }//GEN-LAST:event_addReportTypeTxtKeyTyped

    private void addReportTypeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addReportTypeTxtKeyReleased
        // This should run when a key is released within the text box
        numberOfCharactersInBox = addReportTypeTxt.getText().length();
        if(addReportTypeTxt.getText().length() > 255){
            JOptionPane.showMessageDialog(null, "Please only enter 255 characters");
        }
        addReportCharCountLbl.setText(String.format("%d", numberOfCharactersInBox));
    }//GEN-LAST:event_addReportTypeTxtKeyReleased

    private void addReportTypeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addReportTypeTxtKeyPressed
        // And this should run when a key is pressed within the text box
        numberOfCharactersInBox = addReportTypeTxt.getText().length();
        addReportCharCountLbl.setText(String.format("%d", numberOfCharactersInBox));
    }//GEN-LAST:event_addReportTypeTxtKeyPressed

    private void addReportOpenMainBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportOpenMainBtnMouseClicked
        /*
        In an effort to allow the customer the choice for filling out a full report
        or just having as electronic record of a meeting or handoff, this will show or 
        hide the main report body text box
        */
        if(mainTextVisible){
            setBounds(0, 0, 439, 439);
            addReportMainReportTxtBox.setVisible(false);
            addReportOpenMainBtn.setText("Show Main Report Form");
            mainTextVisible = false;
            
            
            
        }
        else{
            setBounds(0, 0, 966, 439);
            addReportMainReportTxtBox.setVisible(true);
            addReportOpenMainBtn.setText("Hide Main Report Form");
            mainTextVisible = true;
        }
        
    }//GEN-LAST:event_addReportOpenMainBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReportCancelBtn;
    private javax.swing.JLabel addReportCharCountLbl;
    private javax.swing.JButton addReportConfirmBtn;
    private javax.swing.JFormattedTextField addReportDateTxt;
    private javax.swing.JTextArea addReportMainReportTxtBox;
    private javax.swing.JButton addReportOpenMainBtn;
    private javax.swing.JTextArea addReportTypeTxt;
    private javax.swing.JTextPane addReportUserIdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables


}
