/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package msystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class CheckOutScreen extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutScreen
     */
    String sql = null;
    DBConnect db = new DBConnect();
    Connection con = null;
    PreparedStatement stmt;
    ResultSet result;
    
    
    
    public CheckOutScreen() {
        initComponents();
        checkoutEquipNameField.setText(MainPage.getEquipmentName);
        checkoutEquipCharField.setText(MainPage.getEquipmentChar);
        checkoutEquipNumField.setText(MainPage.getEquipmentNum);
        checkoutEquipDescriptionField.setText(MainPage.getEquipmentDescrip);
        
        // populate user id input field with saved user id
        checkoutUserIDField.setText(MainPage.getUserID);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkoutUserIDField = new javax.swing.JTextField();
        checkoutEquipCharField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkoutEquipNumField = new javax.swing.JTextField();
        checkoutCheckOutBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        checkoutEquipNameField = new javax.swing.JTextField();
        checkoutCancelBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        checkoutEquipDescriptionField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("User ID:");

        jLabel3.setText("Equipment ID:");

        jLabel4.setText("-");

        checkoutCheckOutBtn.setText("Check Out");
        checkoutCheckOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutCheckOutBtnMouseClicked(evt);
            }
        });

        jLabel5.setText("Equipment Name:");

        checkoutCancelBtn.setText("Cancel");
        checkoutCancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutCancelBtnMouseClicked(evt);
            }
        });

        jLabel6.setText("Equipment Description:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(checkoutUserIDField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addComponent(checkoutEquipNameField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkoutEquipDescriptionField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkoutCancelBtn)
                                    .addComponent(checkoutEquipCharField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkoutEquipNumField)
                                    .addComponent(checkoutCheckOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(checkoutUserIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(checkoutEquipNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkoutEquipDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(checkoutEquipCharField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(checkoutEquipNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutCancelBtn)
                    .addComponent(checkoutCheckOutBtn))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutCancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutCancelBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MainPage.editEmployee = false;
    }//GEN-LAST:event_checkoutCancelBtnMouseClicked

    private void checkoutCheckOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutCheckOutBtnMouseClicked
        // TODO add your handling code here:
        if (checkoutEquipNameField.getText().isEmpty() || checkoutEquipCharField.getText().isEmpty()
                || checkoutEquipNumField.getText().isEmpty() || checkoutEquipDescriptionField.getText().isEmpty()
                || checkoutUserIDField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all fields.");
        }
        else {
            try {
                con = db.OpenConnection();
                ArrayList<String> elements = new ArrayList<String>();
                String charID = checkoutEquipCharField.getText();
                String numID = checkoutEquipNumField.getText();
                String name = checkoutEquipNameField.getText();
                String descrip = checkoutEquipDescriptionField.getText();
                String userID = checkoutUserIDField.getText();
                
                String pattern = "yyyy-MM-dd";
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                
                String date = simpleDateFormat.format(new Date());
                System.out.println(date);
                
                sql = String.format("UPDATE equipment SET Status = \'Checked out\', Location = \'Out\' WHERE EquipmentIDChar = \'%s\' AND EquipmentIDNum = \'%s\'", charID, numID);
                stmt = con.prepareStatement(sql);

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully checked out equipment.");
                
                sql = String.format("INSERT INTO equipment_checkout (UserID, EquipmentIDChar, EquipmentIDNum, CheckoutDate, Status) VALUES (%s, \'%s\', \'%s\', \'%s\', \'Checked out\')",
                        userID, charID, numID, date);
                
                stmt = con.prepareStatement(sql);
                stmt.execute();
                System.out.println("Success");
                
                this.setVisible(false);
                
            } catch (SQLException ex) {
                Logger.getLogger(CheckOutScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CheckOutScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_checkoutCheckOutBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkoutCancelBtn;
    private javax.swing.JButton checkoutCheckOutBtn;
    private javax.swing.JTextField checkoutEquipCharField;
    private javax.swing.JTextField checkoutEquipDescriptionField;
    private javax.swing.JTextField checkoutEquipNameField;
    private javax.swing.JTextField checkoutEquipNumField;
    private javax.swing.JTextField checkoutUserIDField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
