/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package msystem;

import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;

/**
 *
 * @author never
 */
public class EditEmployee extends javax.swing.JFrame {
    static boolean passwordEdit = false;
    static boolean passAsk = false;
    
    /**
     * Creates new form EditEmployee
     */
    public EditEmployee() {
        initComponents();
        passwordEdit = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editEmpUserIDtxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        editEmpUsernametxt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        editEmpPasswordtxt = new javax.swing.JTextArea();
        editEmpEndorseComboBox = new javax.swing.JComboBox<>();
        editEmpRoleComboBox = new javax.swing.JComboBox<>();
        editEmpConfirmButton = new javax.swing.JButton();
        editEmpCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editEmpUserIDtxt.setColumns(20);
        editEmpUserIDtxt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        editEmpUserIDtxt.setRows(1);
        jScrollPane1.setViewportView(editEmpUserIDtxt);

        editEmpUsernametxt.setColumns(20);
        editEmpUsernametxt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        editEmpUsernametxt.setRows(1);
        jScrollPane2.setViewportView(editEmpUsernametxt);

        editEmpPasswordtxt.setColumns(20);
        editEmpPasswordtxt.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        editEmpPasswordtxt.setRows(1);
        editEmpPasswordtxt.setText("***************");
        editEmpPasswordtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editEmpPasswordtxtFocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(editEmpPasswordtxt);

        editEmpEndorseComboBox.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        editEmpEndorseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        editEmpRoleComboBox.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        editEmpRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Management", "Maintenance", "Warehouse", "Technician" }));
        editEmpRoleComboBox.setSelectedItem("Technician");
        editEmpRoleComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                editEmpRoleComboBoxItemStateChanged(evt);
            }
        });
        editEmpRoleComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                editEmpRoleComboBoxPropertyChange(evt);
            }
        });

        editEmpConfirmButton.setText("Confirm");
        editEmpConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEmpConfirmButtonMouseClicked(evt);
            }
        });

        editEmpCancelButton.setText("Cancel");
        editEmpCancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEmpCancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(editEmpRoleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editEmpEndorseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editEmpConfirmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editEmpCancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editEmpRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editEmpEndorseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmpConfirmButton)
                    .addComponent(editEmpCancelButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editEmpCancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmpCancelButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_editEmpCancelButtonMouseClicked

    private void editEmpConfirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEmpConfirmButtonMouseClicked
        // TODO add your handling code here:
        
        // add the edit sql query here
        // and a confirm popup/toast
        this.setVisible(false);

    }//GEN-LAST:event_editEmpConfirmButtonMouseClicked

    private void editEmpRoleComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_editEmpRoleComboBoxPropertyChange
        // TODO add your handling code here:
        //only need if below method does not work
    }//GEN-LAST:event_editEmpRoleComboBoxPropertyChange

    private void editEmpRoleComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_editEmpRoleComboBoxItemStateChanged
        // TODO add your handling code here:
        
        ArrayList<String> techEndos = new ArrayList<String>();
        ArrayList<String> manageEndos = new ArrayList<String>();
        ArrayList<String> maintEndos = new ArrayList<String>();
        ArrayList<String> wareEndos = new ArrayList<String>();
        
        Collections.addAll(techEndos, "None");
        Collections.addAll(manageEndos, "Staff","Maintenance","Warehouse","Technician");
        Collections.addAll(maintEndos, "Electrician","Machine","Painter","Welder","Plumber","Carpenter","None");
        Collections.addAll(wareEndos, "Inventory","Equipment");
      
        DefaultComboBoxModel tModel = new DefaultComboBoxModel();
        DefaultComboBoxModel bModel = new DefaultComboBoxModel();
        DefaultComboBoxModel mModel = new DefaultComboBoxModel();
        DefaultComboBoxModel aModel = new DefaultComboBoxModel();
        DefaultComboBoxModel wModel = new DefaultComboBoxModel();

        tModel.addAll(techEndos);
        bModel.addAll(manageEndos);
        mModel.addAll(maintEndos);
        aModel.addAll(techEndos);
        wModel.addAll(wareEndos);
        
        if(editEmpRoleComboBox.getSelectedItem().equals("Admin")){
            editEmpEndorseComboBox.setModel(aModel);
            editEmpEndorseComboBox.setSelectedIndex(0);
            System.out.println("Admin detected");
        }
        else if(editEmpRoleComboBox.getSelectedItem().equals("Management")){
            editEmpEndorseComboBox.setModel(bModel);
            editEmpEndorseComboBox.setSelectedIndex(0);
            System.out.println("boss detected");

        }
        else if(editEmpRoleComboBox.getSelectedItem().equals("Maintenance")){
            editEmpEndorseComboBox.setModel(mModel);
            editEmpEndorseComboBox.setSelectedIndex(0);
            System.out.println("maint detected");

        }
        else if(editEmpRoleComboBox.getSelectedItem().equals("Warehouse")){
            editEmpEndorseComboBox.setModel(wModel);
            editEmpEndorseComboBox.setSelectedIndex(0);
            System.out.println("ware detected");

        }
        else if(editEmpRoleComboBox.getSelectedItem().equals("Technician")){
            editEmpEndorseComboBox.setModel(tModel);
            editEmpEndorseComboBox.setSelectedIndex(0);
            System.out.println("tech detected");

        }
    }//GEN-LAST:event_editEmpRoleComboBoxItemStateChanged

    private void editEmpPasswordtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editEmpPasswordtxtFocusGained
        // TODO add your handling code here:
        // toast?
        if(!passwordEdit){
            jScrollPane1.requestFocus();
            new EditEmployeePasswordConfirm().setVisible(true);
            passAsk = true;
            
        }
    }//GEN-LAST:event_editEmpPasswordtxtFocusGained

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new EditEmployee().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editEmpCancelButton;
    private javax.swing.JButton editEmpConfirmButton;
    private javax.swing.JComboBox<String> editEmpEndorseComboBox;
    private javax.swing.JTextArea editEmpPasswordtxt;
    private javax.swing.JComboBox<String> editEmpRoleComboBox;
    private javax.swing.JTextArea editEmpUserIDtxt;
    private javax.swing.JTextArea editEmpUsernametxt;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
