/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package msystem;

/**
 *
 * @author thoma
 */
import java.awt.List;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import msystem.Employee;
import msystem.Equipment;
public class MainPage extends javax.swing.JFrame {
    
    DBConnect db = new DBConnect();
    Connection con = null;
    PreparedStatement stmt;
    ResultSet result;
    Employee emp = new Employee();
    static boolean editEmployee = false;
    String sql = null;
    static String pullThisUserIdForEdit = null;
    static String selectingThisUserID = null;
    static String selectingThisUsername = null;
    static String selectingThisPassword = null;
    static String selectingThisRole = null;
    static String selectingThisEndorsement = null;
    Equipment equip = new Equipment();

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        AccessReportInfo();
        AccessEmployeeInfo();
        AccessInventoryInfo();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tabPanePanel = new javax.swing.JTabbedPane();
        equipmentTab = new javax.swing.JPanel();
        lblToolname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTools = new javax.swing.JList<>();
        lblTooldescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaTooldescription = new javax.swing.JTextArea();
        btnCheckavailable = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        btnCheckin = new javax.swing.JButton();
        btnReportloss = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        inventoryTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtInvSearch = new javax.swing.JTextField();
        btnInventorySearch = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblAdjustments = new javax.swing.JLabel();
        lblInventoryRecord = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txaRecord = new javax.swing.JTextArea();
        txtSearchRecord = new javax.swing.JTextField();
        btnSearchRecord = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        invMainList = new javax.swing.JList<>();
        maintenanceTab = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        maintSearchEmpBtn = new javax.swing.JButton();
        maintSearchCatBtn = new javax.swing.JButton();
        maintSearchDateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        maintLogBtn = new javax.swing.JButton();
        reportTab = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reportList = new javax.swing.JList<>();
        reportListLabel = new javax.swing.JLabel();
        reportSearchField = new javax.swing.JTextField();
        reportSearchBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        reportDetailsField = new javax.swing.JTextArea();
        reportPrint = new javax.swing.JButton();
        reportLoadAllBtn = new javax.swing.JButton();
        Employee = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        empList = new javax.swing.JList<>();
        empListLabel = new javax.swing.JLabel();
        empFirstNameSearchField = new javax.swing.JTextField();
        empSearchBtn = new javax.swing.JButton();
        empAddBtn = new javax.swing.JButton();
        empRemoveBtn = new javax.swing.JButton();
        empEditBtn = new javax.swing.JButton();
        empLastInitSearchField = new javax.swing.JTextField();
        empLoadAllBtn = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        logOutBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblToolname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToolname.setText("Tool Name:");

        lstTools.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        lstTools.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstTools);

        lblTooldescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTooldescription.setText("Tool Description:");

        txaTooldescription.setColumns(30);
        txaTooldescription.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        txaTooldescription.setRows(5);
        jScrollPane2.setViewportView(txaTooldescription);

        btnCheckavailable.setText("Check");

        btnCheckout.setText("Check Out");

        btnCheckin.setText("Check In");

        btnReportloss.setBackground(new java.awt.Color(255, 51, 51));
        btnReportloss.setText("REPORT LOST");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tool Summary:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout equipmentTabLayout = new javax.swing.GroupLayout(equipmentTab);
        equipmentTab.setLayout(equipmentTabLayout);
        equipmentTabLayout.setHorizontalGroup(
            equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentTabLayout.createSequentialGroup()
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnCheckavailable))
                    .addGroup(equipmentTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReportloss)))
                .addGap(115, 115, 115)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckout)
                    .addComponent(btnCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equipmentTabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblToolname)
                .addGap(125, 125, 125)
                .addComponent(lblTooldescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equipmentTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        equipmentTabLayout.setVerticalGroup(
            equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipmentTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToolname)
                    .addComponent(lblTooldescription)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckavailable)
                    .addComponent(btnCheckout))
                .addGap(18, 18, 18)
                .addGroup(equipmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckin)
                    .addComponent(btnReportloss))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        tabPanePanel.addTab("Epuipment", equipmentTab);

        jLabel2.setText("Inventory:");

        txaInventory.setColumns(20);
        txaInventory.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        txaInventory.setRows(5);
        jScrollPane9.setViewportView(txaInventory);


        btnInventorySearch.setText("Search");
        btnInventorySearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventorySearchMouseClicked(evt);
            }
        });

        jList2.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList2);

        btnAdd.setText("Add");

        btnDelete.setText("Delete");

        lblAdjustments.setText("Adjustments:");

        lblInventoryRecord.setText("Inventory Record");

        txaRecord.setColumns(20);
        txaRecord.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        txaRecord.setRows(5);
        jScrollPane10.setViewportView(txaRecord);

        btnSearchRecord.setText("Search");

        invMainList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(invMainList);

        javax.swing.GroupLayout inventoryTabLayout = new javax.swing.GroupLayout(inventoryTab);
        inventoryTab.setLayout(inventoryTabLayout);
        inventoryTabLayout.setHorizontalGroup(
            inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryTabLayout.createSequentialGroup()

                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryTabLayout.createSequentialGroup()
                        .addComponent(txtInvSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInventorySearch))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inventoryTabLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnAdd)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelete))
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAdjustments))
                .addGap(18, 18, 18)
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInventoryRecord)
                    .addGroup(inventoryTabLayout.createSequentialGroup()
                        .addComponent(txtSearchRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                        .addComponent(btnSearchRecord)))
                .addGap(19, 19, 19))

        );
        inventoryTabLayout.setVerticalGroup(
            inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAdjustments)
                    .addComponent(lblInventoryRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jScrollPane11))
                .addGap(20, 20, 20)
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventorySearch)
                    .addComponent(btnDelete)
                    .addComponent(txtSearchRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(btnSearchRecord)
                    .addComponent(btnAdd))
                .addContainerGap(49, Short.MAX_VALUE))

        );

        tabPanePanel.addTab("Inventory", inventoryTab);

        maintSearchEmpBtn.setText("Search by Employee ID");

        maintSearchCatBtn.setText("Search by Category");

        maintSearchDateBtn.setText("Search by Date");

        jLabel3.setText("Maintenance Logs:");

        jList1.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList1);

        maintLogBtn.setText("New Log");

        javax.swing.GroupLayout maintenanceTabLayout = new javax.swing.GroupLayout(maintenanceTab);
        maintenanceTab.setLayout(maintenanceTabLayout);
        maintenanceTabLayout.setHorizontalGroup(
            maintenanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maintenanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maintenanceTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(maintenanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maintSearchEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(maintSearchCatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maintSearchDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maintLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(maintenanceTabLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        maintenanceTabLayout.setVerticalGroup(
            maintenanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maintenanceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(maintenanceTabLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maintSearchEmpBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maintSearchCatBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maintSearchDateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maintLogBtn))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tabPanePanel.addTab("Maintenance", maintenanceTab);

        reportList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reportListValueChanged(evt);
            }

        });
        jScrollPane4.setViewportView(reportList);

        reportListLabel.setText("Report List:");

        reportSearchField.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N

        reportSearchBtn.setText("Search");
        reportSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportSearchBtnMouseClicked(evt);
            }
        });

        reportDetailsField.setColumns(20);
        reportDetailsField.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        reportDetailsField.setRows(5);
        jScrollPane5.setViewportView(reportDetailsField);

        reportPrint.setText("Print");
        reportPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportPrintMouseClicked(evt);
            }
        });

        reportLoadAllBtn.setText("Load All");
        reportLoadAllBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportLoadAllBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reportTabLayout = new javax.swing.GroupLayout(reportTab);
        reportTab.setLayout(reportTabLayout);
        reportTabLayout.setHorizontalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportTabLayout.createSequentialGroup()
                        .addComponent(reportListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(reportTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reportTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(reportTabLayout.createSequentialGroup()
                                        .addComponent(reportSearchField)
                                        .addGap(18, 18, 18)
                                        .addComponent(reportSearchBtn))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)))
                            .addGroup(reportTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reportLoadAllBtn)
                                .addGap(18, 18, 18)
                                .addComponent(reportPrint)))))
                .addContainerGap())
        );
        reportTabLayout.setVerticalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportTabLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(reportListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportTabLayout.createSequentialGroup()
                        .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportSearchBtn))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportPrint)
                    .addComponent(reportLoadAllBtn))
                .addGap(15, 15, 15))
        );

        tabPanePanel.addTab("Report", reportTab);

        empList.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        empList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        empList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                empListValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(empList);

        empListLabel.setText("Employees List:");

        empFirstNameSearchField.setText("First Name");
        empFirstNameSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empFirstNameSearchFieldFocusGained(evt);
            }
        });

        empSearchBtn.setText("Search");
        empSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empSearchBtnMouseClicked(evt);
            }
        });

        empAddBtn.setText("Add");
        empAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empAddBtnMouseClicked(evt);
            }
        });

        empRemoveBtn.setText("Remove");
        empRemoveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empRemoveBtnMouseClicked(evt);
            }
        });

        empEditBtn.setText("Edit");
        empEditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empEditBtnMouseClicked(evt);
            }
        });

        empLoadAllBtn.setText("Load All");
        empLoadAllBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empLoadAllBtnMouseClicked(evt);
            }
        });

        empLastInitSearchField.setText("Last Initial");
        empLastInitSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empLastInitSearchFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout EmployeeLayout = new javax.swing.GroupLayout(Employee);
        Employee.setLayout(EmployeeLayout);
        EmployeeLayout.setHorizontalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(EmployeeLayout.createSequentialGroup()
                        .addComponent(empListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EmployeeLayout.createSequentialGroup()
                        .addComponent(empFirstNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empLastInitSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empSearchBtn)
                        .addGap(18, 18, 18)

                        .addComponent(empLoadAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)

                        .addComponent(empAddBtn)
                        .addGap(18, 18, 18)
                        .addComponent(empEditBtn)
                        .addGap(18, 18, 18)
                        .addComponent(empRemoveBtn)))
                .addContainerGap())
        );
        EmployeeLayout.setVerticalGroup(
            EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(EmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empFirstNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empSearchBtn)
                    .addComponent(empAddBtn)
                    .addComponent(empRemoveBtn)
                    .addComponent(empEditBtn)

                    .addComponent(empLastInitSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addComponent(empLoadAllBtn))

                .addGap(16, 16, 16))
        );

        tabPanePanel.addTab("Employee", Employee);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanePanel)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanePanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        logOutBtn.setText("Log Out");
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutBtnMouseClicked(evt);
            }
        });
        mainMenuBar.add(logOutBtn);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new UserAuth().setVisible(true);
    }//GEN-LAST:event_logOutBtnMouseClicked

    private void empLoadAllBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empLoadAllBtnMouseClicked
        // TODO add your handling code here:
        AccessEmployeeInfo();
    }//GEN-LAST:event_empLoadAllBtnMouseClicked

    private void empEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empEditBtnMouseClicked
        // TODO add your handling code here:
        // Connect to EditEmployee Form
        this.setVisible(false);
        new EditEmployee().setVisible(true);
    }//GEN-LAST:event_empEditBtnMouseClicked

    private void reportLoadAllBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLoadAllBtnMouseClicked
        // TODO add your handling code here:
        AccessReportInfo();
    }//GEN-LAST:event_reportLoadAllBtnMouseClicked

    private void reportSearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportSearchBtnMouseClicked
        // TODO add your handling code here:
        ArrayList<String> list = new ArrayList<String>();
        try {
            int input = Integer.parseInt(reportSearchField.getText());
            try {
                list = emp.SearchReports(input);
                DefaultListModel model = new DefaultListModel();
                model.addAll(list);
                reportList.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please enter a valid User ID");
        }
    }//GEN-LAST:event_reportSearchBtnMouseClicked

    private void reportPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPrintMouseClicked
        // TODO add info from details box into a new form that will be saved as a file to the user's device.
    }//GEN-LAST:event_reportPrintMouseClicked

    private void reportListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reportListValueChanged
        try {
            // TODO add your handling code here:
            ViewReportDetails();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reportListValueChanged

    private void btnInventorySearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventorySearchMouseClicked
        // TODO add your handling code here:
        if (txtInvSearch.getText().equals("")) {
            System.out.println("Search successful");
            AccessInventoryInfo();
        }
    }//GEN-LAST:event_btnInventorySearchMouseClicked

    private void empEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empEditBtnMouseClicked
        // TODO add your handling code here:
        //this.setVisible(false);
        editEmployee = true;
        ArrayList<String> list = new ArrayList<String>();
        try {
            list = emp.PullEmpInfo(pullThisUserIdForEdit);
            selectingThisUserID = pullThisUserIdForEdit;
            selectingThisUsername = list.get(1);
            selectingThisPassword = null;
            selectingThisRole = list.get(2);
            selectingThisEndorsement = list.get(3);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        new EditEmployee().setVisible(true);
        
        
    }//GEN-LAST:event_empEditBtnMouseClicked

    private void empAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empAddBtnMouseClicked
        // TODO add your handling code here:
        new EditEmployee().setVisible(true);
        EditEmployee.passwordEdit = true;
    }//GEN-LAST:event_empAddBtnMouseClicked

    private void empRemoveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empRemoveBtnMouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showInputDialog("Are you sure you want to delete this user? Please enter DELETE to confirm action (case specific)").equals("DELETE")){
            emp.RemoveEmpInfo(pullThisUserIdForEdit);
            //sql = String.format("DELETE FROM user_authoization WHERE UserID = %s", pullThisUserIdForEdit);
            //System.out.println(sql);
            
            //JOptionPane.showMessageDialog(null, sql);
        }
        else{
            JOptionPane.showMessageDialog(null, "Data not removed, confirmation entered incorrectly");
        }
    }//GEN-LAST:event_empRemoveBtnMouseClicked

    private void empListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_empListValueChanged
        // TODO add your handling code here:
        //adding all code of selecting item here in order to not run it multiple times via the edit and delete button
        String test = empList.getSelectedValue();
        //trying to split this string into a list using .spit(",")
        if(test != null){
            var Test = new ArrayList<String>(Arrays.asList(test.split(",")));
            pullThisUserIdForEdit = Test.get(0).trim();
            System.out.println(pullThisUserIdForEdit);
        }
    }//GEN-LAST:event_empListValueChanged

    private void empSearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empSearchBtnMouseClicked
        // TODO add your handling code here:
        String searchFirstNameText = empFirstNameSearchField.getText().trim();
        String searchLastInitText = empLastInitSearchField.getText().trim();
        String searchText = null;
        boolean fName = false;
        boolean lName = false;
        
        if(!searchFirstNameText.equals("") && !searchFirstNameText.equals("First Name")){
            //System.out.println(searchFirstNameText);
            fName = true;
            searchText = searchFirstNameText;
        }
        if(!searchLastInitText.equals("") && !searchLastInitText.equals("Last Initial")){
            //System.out.println(searchLastInitText);
            lName = true;
            searchText = String.format("%s%s", searchText, searchLastInitText);
        }
        System.out.println(searchText);
        if(!fName && !lName){
            return;
        }
        ArrayList<String> list = new ArrayList<String>();
        try {
            list = emp.SearchEmployees(fName, lName, searchFirstNameText, searchLastInitText);
            DefaultListModel model = new DefaultListModel();
            model.addAll(list);
            empList.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_empSearchBtnMouseClicked

    private void empFirstNameSearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empFirstNameSearchFieldFocusGained
        // TODO add your handling code here:
        if(!empFirstNameSearchField.getText().equals("")){
            empFirstNameSearchField.setText("");
        }
    }//GEN-LAST:event_empFirstNameSearchFieldFocusGained

    private void empLastInitSearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empLastInitSearchFieldFocusGained
        // TODO add your handling code here:
        if(!empLastInitSearchField.getText().equals("")){
            empLastInitSearchField.setText("");
        }
    }//GEN-LAST:event_empLastInitSearchFieldFocusGained

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    
    public void AccessEquipmentInfo() {
        
    }
    
    public void AccessInventoryInfo() {
        ArrayList<String> list = new ArrayList<String>();
        try {
            list = equip.ViewInventory();
            DefaultListModel model = new DefaultListModel();
            model.addAll(list);
            invMainList.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void AccessEmployeeInfo() {
        ArrayList<String> list = new ArrayList<String>();
        try {
            list = emp.PullEmployees();
            DefaultListModel model = new DefaultListModel();
            model.addAll(list);
            empList.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void AccessReportInfo() {
        ArrayList<String> list = new ArrayList<String>();
        try {
            list = emp.PullReports();
            DefaultListModel model = new DefaultListModel();
            model.addAll(list);
            reportList.setModel(model);
            reportSearchField.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    public void ViewReportDetails() throws ClassNotFoundException {
        String list = "Nothing";
        try {
            list = emp.ReportDetails(reportList.getSelectedValue());
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        reportDetailsField.setText(list);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Employee;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCheckavailable;
    private javax.swing.JButton btnCheckin;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInventorySearch;
    private javax.swing.JButton btnReportloss;
    private javax.swing.JButton btnSearchRecord;
    private javax.swing.JButton empAddBtn;
    private javax.swing.JButton empEditBtn;
    private javax.swing.JTextField empFirstNameSearchField;
    private javax.swing.JTextField empLastInitSearchField;
    private javax.swing.JList<String> empList;
    private javax.swing.JLabel empListLabel;
    private javax.swing.JButton empLoadAllBtn;
    private javax.swing.JButton empRemoveBtn;
    private javax.swing.JButton empSearchBtn;
    private javax.swing.JPanel equipmentTab;
    private javax.swing.JList<String> invMainList;
    private javax.swing.JPanel inventoryTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAdjustments;
    private javax.swing.JLabel lblInventoryRecord;
    private javax.swing.JLabel lblTooldescription;
    private javax.swing.JLabel lblToolname;
    private javax.swing.JMenu logOutBtn;
    private javax.swing.JList<String> lstTools;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton maintLogBtn;
    private javax.swing.JButton maintSearchCatBtn;
    private javax.swing.JButton maintSearchDateBtn;
    private javax.swing.JButton maintSearchEmpBtn;
    private javax.swing.JPanel maintenanceTab;
    private javax.swing.JTextArea reportDetailsField;
    private javax.swing.JList<String> reportList;
    private javax.swing.JLabel reportListLabel;
    private javax.swing.JButton reportLoadAllBtn;
    private javax.swing.JButton reportPrint;
    private javax.swing.JButton reportSearchBtn;
    private javax.swing.JTextField reportSearchField;
    private javax.swing.JPanel reportTab;
    private javax.swing.JTabbedPane tabPanePanel;
    private javax.swing.JTextArea txaRecord;
    private javax.swing.JTextArea txaTooldescription;
    private javax.swing.JTextField txtInvSearch;
    private javax.swing.JTextField txtSearchRecord;
    // End of variables declaration//GEN-END:variables

    private void setVisisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
